#!/usr/bin/env python3
"""Records the build-fact probe's rows into docs/build-facts.md.

tests/boys_build_facts.cpp states what one build is - the instruction sets it
targets, whether a bare `a * b + c` in it is a single rounding, whether the
library's objects call an out-of-line fma, which arithmetic backends it carries
- one line per fact. This script is how those statements reach the table: the
probe's output is captured from a build, folded in here, and committed. Every
CI leg then runs the probe with --check, which compares the live facts against
the row recorded for that leg and fails the leg when a *fact* moves.

The rows are the source of truth and they live in the document, so --record
merges into what is already recorded and --check re-renders the document from
its own rows: a hand edit to the generated region is drift, and so is a leg in
ci.yml that the table does not account for.

Usage:
    python tools/gen_build_facts.py --record build-facts-windows.txt ...
    python tools/gen_build_facts.py --check
"""

import argparse
import datetime
import pathlib
import sys

# The CI matrix is read in one place, by the tool that generates the README's
# supported-platform table. Importing it rather than parsing ci.yml a second
# time keeps one answer to "which legs are there and what runner does each use".
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import gen_platform_table as platform

REPO = pathlib.Path(__file__).resolve().parent.parent
DOC = REPO / "docs" / "build-facts.md"

BEGIN = "<!-- build-facts:begin (generated by tools/gen_build_facts.py; do not edit) -->"
END = "<!-- build-facts:end -->"

# The format tag the probe prints first. A block that does not carry it is not
# a row, which is what lets the document hold prose and examples beside the
# generated ones.
FORMAT = "boys.build-facts/1"


def ci_legs():
    """Every CI leg as a dict: check name -> runner label, in workflow order."""
    return {name: runner for name, runner, _ in platform.legs()}


def facts_from(entries):
    """One row's `key=value` lines as (leg, facts).

    Raises SystemExit on a malformed row: a line that is not key=value, or a
    row without exactly one leg. Such a row would otherwise be dropped or
    mis-keyed in silence, and the table would say less than it appears to.
    """
    facts = []
    for entry in entries:
        if "=" not in entry:
            raise SystemExit(
                f"gen_build_facts: a {FORMAT} row carries a line that is not "
                f"key=value: {entry!r}")
        key, value = entry.split("=", 1)
        facts.append((key.strip(), value.strip()))
    legs = [value for key, value in facts if key == "leg"]
    if len(legs) != 1:
        raise SystemExit(
            f"gen_build_facts: a {FORMAT} row carries {len(legs)} leg lines; "
            "exactly one is required")
    return legs[0], facts


def parse_blocks(text):
    """The recorded rows: leg -> list of (key, value) pairs, in document order."""
    rows = {}
    in_block = False
    body = []
    for line in text.splitlines():
        if not in_block:
            if line.strip() == "```text":
                in_block = True
                body = []
            continue
        if line.strip() == "```":
            in_block = False
            if body and body[0] == FORMAT:
                leg, facts = facts_from(body[1:])
                rows[leg] = facts
            continue
        body.append(line.strip())
    return rows


def render_block(leg, facts, runner):
    heading = f"#### `{leg}`"
    if runner:
        heading += f" — runner label `{runner}`"
    fence = "\n".join([FORMAT] + [f"{key}={value}" for key, value in facts])
    return f"{heading}\n\n```text\n{fence}\n```"


def render(rows):
    """The generated region: recorded rows, then the legs that have none."""
    legs = ci_legs()
    recorded_legs = [name for name in legs if name in rows]
    other_legs = sorted(name for name in rows if name not in legs)
    missing_legs = [name for name in legs if name not in rows]

    if other_legs:
        summary = (f"{len(recorded_legs)} of the {len(legs)} CI legs have a row "
                   f"here, and {len(other_legs)} row(s) were recorded from builds "
                   "that are not CI legs.")
    else:
        summary = f"{len(recorded_legs)} of the {len(legs)} CI legs have a row here."

    parts = [summary, "",
             "Each row was observed by the build it describes, and the lines a row "
             "carries are the facts of that one build.", ""]

    for leg in recorded_legs:
        parts.append(render_block(leg, rows[leg], legs[leg]))
        parts.append("")
    for leg in other_legs:
        parts.append(render_block(leg, rows[leg], None))
        parts.append("")

    parts.append("### CI legs with no recorded row yet")
    parts.append("")
    if not missing_legs:
        parts.append("None: every leg of the matrix has a row.")
    else:
        parts.append(
            "Each of these legs prints its own row on its next run, under the "
            "step that runs the probe. Record it with")
        parts.append("")
        parts.append("    python tools/gen_build_facts.py --record <the captured block>")
        parts.append("")
        parts.append("| CI leg | Runner label |")
        parts.append("|---|---|")
        for leg in missing_legs:
            parts.append(f"| `{leg}` | `{legs[leg]}` |")
    parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def splice(text, block):
    if BEGIN not in text or END not in text:
        raise SystemExit(f"gen_build_facts: {DOC} has no build-facts markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{BEGIN}\n{block}{END}{tail}"


def read_captured(path):
    """One captured probe output as (leg, facts), with the recording stamped.

    A capture is the probe's own output, so it may be the bare row rather than
    a fenced block: everything from the format tag to the first line that is
    not key=value is the row, which also stops at the fence of a row copied out
    of this document and at any of the probe's own report lines.

    The stamp is dated here rather than by the probe: the table is a record of
    what was observed and when, and the probe itself reads no clock.
    """
    lines = [line.strip() for line in
             path.read_text(encoding="utf-8", errors="replace").splitlines()]
    if FORMAT not in lines:
        raise SystemExit(f"gen_build_facts: {path} carries no {FORMAT} row")
    entries = []
    for line in lines[lines.index(FORMAT) + 1:]:
        if "=" not in line:
            break
        entries.append(line)
    leg, facts = facts_from(entries)
    if not any(key == "recorded" for key, _ in facts):
        facts = facts + [("recorded", datetime.date.today().isoformat())]
    return leg, facts


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--record", nargs="+", type=pathlib.Path,
                        help="captured probe output(s) to fold into the table")
    parser.add_argument("--check", action="store_true",
                        help="exit nonzero if the table is out of date")
    args = parser.parse_args()
    if args.record and args.check:
        parser.error("--record and --check are different acts; pass one")

    current = DOC.read_text(encoding="utf-8")

    if args.check:
        updated = splice(current, render(parse_blocks(current)))
        if current != updated:
            print("DRIFT: docs/build-facts.md is not what its own rows and "
                  "ci.yml render", file=sys.stderr)
            return 1
        rows = parse_blocks(current)
        legs = ci_legs()
        recorded = sum(1 for leg in legs if leg in rows)
        print(f"docs/build-facts.md matches its rows: {recorded} of {len(legs)} "
              f"CI legs recorded, {len(rows) - recorded} row(s) from other builds")
        return 0

    if not args.record:
        parser.error("pass --record <file> or --check")

    rows = parse_blocks(current)
    for path in args.record:
        leg, facts = read_captured(path)
        rows[leg] = facts
        print(f"recorded {leg} from {path}")

    DOC.write_text(splice(current, render(rows)), encoding="utf-8", newline="\n")
    print(f"wrote the build-fact table into {DOC.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
