#!/usr/bin/env python3
"""Generates the supported-platform table in README.md from the CI workflow.

The table's rows ARE the CI matrix, and its "required" column is
.github/required-checks.txt, which is the same list the branch-protection rule
on main names. Hand-writing either would let the README advertise a platform
nothing builds, or a leg a PR is not actually gated on; generating them means
the README can only say what the workflow does, and --check (run by the CI
legs) fails the build when the two drift apart.

The AVX2 column comes from each leg's own `expect_avx2` matrix value, which is
the expectation that leg's dispatch assertion holds itself to (see
tests/boys_avx2_probe.cpp) - not an inference from the runner's name.

Usage:
    python tools/gen_platform_table.py            # rewrite the README block
    python tools/gen_platform_table.py --check    # fail if it is out of date
"""

import argparse
import json
import pathlib
import sys

import yaml

REPO = pathlib.Path(__file__).resolve().parent.parent
CI_YML = REPO / ".github" / "workflows" / "ci.yml"
REQUIRED = REPO / ".github" / "required-checks.txt"
README = REPO / "README.md"
OPTION_MATRIX = REPO / ".github" / "option-matrix.json"

BEGIN = "<!-- platform-table:begin (generated by tools/gen_platform_table.py; do not edit) -->"
END = "<!-- platform-table:end -->"


def expand(template, matrix):
    """Resolves the `${{ matrix.<key> }}` expressions a job name may carry.

    Anything else is a hard error: a table that silently renders an unresolved
    expression is worse than no table.
    """
    text = str(template)
    while "${{" in text:
        start = text.index("${{")
        end = text.index("}}", start)
        expression = text[start + 4:end].strip()
        if not expression.startswith("matrix."):
            raise SystemExit(f"gen_platform_table: cannot resolve {expression!r} "
                             f"in {template!r} - teach this script about it")
        key = expression[len("matrix."):]
        if key not in matrix:
            raise SystemExit(f"gen_platform_table: {expression!r} is not in the "
                             f"matrix entry {matrix!r}")
        text = text[:start] + str(matrix[key]) + text[end + 2:]
    return text


def required_set():
    if not REQUIRED.exists():
        raise SystemExit(f"gen_platform_table: {REQUIRED} is missing")
    names = []
    for raw in REQUIRED.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            names.append(line)
    return names


def matrix_entries(job):
    """One job's matrix entries.

    A job states its entries inline, or generates them - the option matrix is
    committed data the workflow expands, so a job whose matrix is a
    `${{ fromJSON(...) }}` expression has no include to read here and its
    entries are that file's. Reading the file the workflow reads keeps the
    table and the run from disagreeing about which legs exist.
    """
    matrix = (job.get("strategy") or {}).get("matrix") or {}
    if not isinstance(matrix, dict):
        if not OPTION_MATRIX.exists():
            raise SystemExit(f"gen_platform_table: {OPTION_MATRIX} is missing, "
                             "and a job generates its matrix from it")
        data = json.loads(OPTION_MATRIX.read_text(encoding="utf-8"))
        return data["configurations"]
    return matrix.get("include") or [{}]


def legs():
    """Every CI leg, in workflow order, as (check name, runner, avx2 tier)."""
    workflow = yaml.safe_load(CI_YML.read_text(encoding="utf-8"))
    rows = []
    for job_id, job in workflow["jobs"].items():
        name = job.get("name", job_id)
        for entry in matrix_entries(job):
            rows.append((expand(name, entry), expand(job["runs-on"], entry),
                         entry.get("expect_avx2")))
    return rows


def render():
    required = required_set()
    rows = legs()
    names = [name for name, _, _ in rows]
    unknown = [name for name in required if name not in names]
    if unknown:
        raise SystemExit("gen_platform_table: required-checks.txt names no leg "
                         f"in ci.yml: {unknown}")

    lines = ["| CI leg (the check name) | Runner | AVX2 tier | Required |",
             "|---|---|---|---|"]
    for name, runner, expect_avx2 in rows:
        if expect_avx2 is None:
            tier = "n/a"
        else:
            tier = "present" if int(expect_avx2) != 0 else "absent"
        lines.append(f"| `{name}` | `{runner}` | {tier} | "
                     f"{'yes' if name in required else 'no'} |")
    return "\n".join(lines)


def splice(text, block):
    if BEGIN not in text or END not in text:
        raise SystemExit(f"gen_platform_table: {README} has no platform-table "
                         "markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return f"{head}{BEGIN}\n{block}\n{END}{tail}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="exit nonzero if the README block is out of date")
    args = parser.parse_args()

    current = README.read_text(encoding="utf-8")
    updated = splice(current, render())

    if args.check:
        if current != updated:
            print("DRIFT: README.md's platform table is not what ci.yml and "
                  "required-checks.txt generate", file=sys.stderr)
            return 1
        print("README platform table matches ci.yml + required-checks.txt")
        return 0

    README.write_text(updated, encoding="utf-8", newline="\n")
    print(f"wrote the platform table into {README.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
